DROP TABLE IF EXISTS `comment`
DROP TABLE IF EXISTS `article_tag_map`
DROP TABLE IF EXISTS `article`
DROP TABLE IF EXISTS `menu`
DROP TABLE IF EXISTS `role`
DROP TABLE IF EXISTS `user`
DROP TABLE IF EXISTS `tag`
DROP TABLE IF EXISTS `guestbook`